version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend_container
    ports:
      - "8120:8120"
    command: uvicorn main:app --host 0.0.0.0 --port 8120
    networks:
      - monitoring-net
  # =================================================================
  # Service: Prometheus
  # =================================================================
  prometheus:
    image: prom/prometheus:v3.4.0
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/alert.rules.yml:/etc/prometheus/alert.rules.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - '9090:9090'
    networks:
      - monitoring-net
    # depends_on:
    #   - backend

  # =================================================================
  # Service: Alertmanager
  # =================================================================
  alertmanager:
    image: prom/alertmanager:v0.28.1
    container_name: alertmanager
    restart: unless-stopped
    volumes:
      - ./prometheus/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
      - alertmanager_data:/alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
    ports:
      - '9093:9093'
    networks:
      - monitoring-net
    depends_on:
      - prometheus

  # =================================================================
  # Service: Node Exporter
  # =================================================================
  node_exporter:
    image: prom/node-exporter:v1.9.1
    container_name: node_exporter
    restart: unless-stopped
    # Node Exporter expose port 9100
    ports:
      - '9100:9100'
    networks:
      - monitoring-net
    # Để Node Exporter có thể đo đạc host metrics (nếu chạy trên host),
    # bạn có thể cần mount pid và root filesystem:
    # pid: "host"
    # network_mode: "host"
    # volumes:
    #   - /proc:/host/proc:ro
    #   - /sys:/host/sys:ro


  # =================================================================
  # (Tùy chọn) Service: Grafana (nếu bạn muốn dashboard)
  # =================================================================
  grafana:
    image: grafana/grafana:12.0.1
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - grafana_storage:/var/lib/grafana
      - ./grafana/dashboard.json:/etc/grafana/dashboard.json:ro
    networks:
      - monitoring-net
    depends_on:
      - prometheus

networks:
  monitoring-net:
    driver: bridge

volumes:
  prometheus_data:
  alertmanager_data:
  grafana_storage:
