global:
  resolve_timeout: 5m

  # Cấu hình SMTP mặc định, áp dụng cho mọi email_configs
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'your_email'
  smtp_auth_username: 'your_email'
  smtp_auth_password: 'your_app_password'     
  smtp_require_tls: true

route:
  receiver: email-critical          # mặc định
  group_by:  ['alertname', 'instance']
  group_wait: 15s
  group_interval: 1m
  repeat_interval: 1m

  # Phân luồng theo severity
  routes:
    - receiver: email-warning
      matchers:
        - severity="warning"
    - receiver: email-critical
      matchers:
        - severity="critical"

receivers:
  - name: email-warning
    email_configs:
      - to: 'your_receive_email'
        send_resolved: true
        headers:
          subject: '[WARNING] {{ .CommonAnnotations.summary }}'

  - name: email-critical
    email_configs:
      - to: 'your_receive_email'
        send_resolved: true
        headers:
          subject: '[CRITICAL] {{ .CommonAnnotations.summary }}'