global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']     # Đặt hostname "alertmanager" vì Docker Compose sẽ đặt network alias

rule_files:
  - "/etc/prometheus/alert.rules.yml"    # file alert.rule trong container

scrape_configs:
  # # 1. Scrape chính Prometheus (để biết prometheus vẫn alive)
  # - job_name: "app"
  #   static_configs:
  #     - targets: ["backend:8120"]  

  # 2. Scrape Node Exporter (system metrics)
  - job_name: "node_exporter"
    static_configs:
      - targets: ["node_exporter:9100"]    # “node_exporter” sẽ là service name trong Compose

  # 3. API 
  - job_name: "api"
    metrics_path: /metrics
    static_configs:
      - targets: ["backend_container:8120"]
