{
 "title": "CPU resources",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "CPU Resources",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "irate(node_cpu_seconds_total{mode!=\"idle\", cpu=\"0\"}[1m])",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Ram Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes)*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk I/O Time Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{device=\"sdd\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Space Available (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 7 },
   "targets": [
    {
     "expr": "100 * (node_filesystem_avail_bytes / node_filesystem_size_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 7 },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device!~\"lo|bond.*|veth.*\"}[5m])",
     "legendFormat": "node_network_receive_bytes_total"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{device!~\"lo|bond.*|veth.*\"}[5m])",
     "legendFormat": "node_network_transmit_bytes_tota"
    }
   ]
  },
  {
   "title": "API Request Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 15 },
   "targets": [
    { "expr": "request_count_total", "legendFormat": "API Request" }
   ]
  },
  {
   "title": "API Error Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 15 },
   "targets": [
    { "expr": "error_count_total", "legendFormat": "API Error Count" }
   ]
  },
  {
   "title": "Latency ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 15 },
   "targets": [
    { "expr": "request_latency_seconds_sum", "legendFormat": "request_latency_seconds_sum" }
   ]
  },
  {
   "title": "Model's Confidence Score (%)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "prediction_confidence * 100", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Inference Time (s)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "inference_time_seconds_sum", "legendFormat": "__auto" }
   ]
  }
 ]
}